// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CD.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Deployment struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Branch               string   `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
	RepoID               int64    `protobuf:"varint,3,opt,name=RepoID,proto3" json:"RepoID,omitempty"`
	ArtifactID           int64    `protobuf:"varint,4,opt,name=ArtifactID,proto3" json:"ArtifactID,omitempty"`
	K8SName              string   `protobuf:"bytes,5,opt,name=K8SName,proto3" json:"K8SName,omitempty"`
	Manifest             string   `protobuf:"bytes,6,opt,name=Manifest,proto3" json:"Manifest,omitempty"`
	Replicas             int64    `protobuf:"varint,7,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_CD_ade787ddd40b394c, []int{0}
}
func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (dst *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(dst, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Deployment) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Deployment) GetRepoID() int64 {
	if m != nil {
		return m.RepoID
	}
	return 0
}

func (m *Deployment) GetArtifactID() int64 {
	if m != nil {
		return m.ArtifactID
	}
	return 0
}

func (m *Deployment) GetK8SName() string {
	if m != nil {
		return m.K8SName
	}
	return ""
}

func (m *Deployment) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *Deployment) GetReplicas() int64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

type DeploymentsQuery struct {
	Page                 int64    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeploymentsQuery) Reset()         { *m = DeploymentsQuery{} }
func (m *DeploymentsQuery) String() string { return proto.CompactTextString(m) }
func (*DeploymentsQuery) ProtoMessage()    {}
func (*DeploymentsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_CD_ade787ddd40b394c, []int{1}
}
func (m *DeploymentsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentsQuery.Unmarshal(m, b)
}
func (m *DeploymentsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentsQuery.Marshal(b, m, deterministic)
}
func (dst *DeploymentsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentsQuery.Merge(dst, src)
}
func (m *DeploymentsQuery) XXX_Size() int {
	return xxx_messageInfo_DeploymentsQuery.Size(m)
}
func (m *DeploymentsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentsQuery proto.InternalMessageInfo

func (m *DeploymentsQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DeploymentsQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DeploymentsArray struct {
	Deployments          []*Deployment `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeploymentsArray) Reset()         { *m = DeploymentsArray{} }
func (m *DeploymentsArray) String() string { return proto.CompactTextString(m) }
func (*DeploymentsArray) ProtoMessage()    {}
func (*DeploymentsArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_CD_ade787ddd40b394c, []int{2}
}
func (m *DeploymentsArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentsArray.Unmarshal(m, b)
}
func (m *DeploymentsArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentsArray.Marshal(b, m, deterministic)
}
func (dst *DeploymentsArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentsArray.Merge(dst, src)
}
func (m *DeploymentsArray) XXX_Size() int {
	return xxx_messageInfo_DeploymentsArray.Size(m)
}
func (m *DeploymentsArray) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentsArray.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentsArray proto.InternalMessageInfo

func (m *DeploymentsArray) GetDeployments() []*Deployment {
	if m != nil {
		return m.Deployments
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_CD_ade787ddd40b394c, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Deployment)(nil), "types.Deployment")
	proto.RegisterType((*DeploymentsQuery)(nil), "types.DeploymentsQuery")
	proto.RegisterType((*DeploymentsArray)(nil), "types.DeploymentsArray")
	proto.RegisterType((*Empty)(nil), "types.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CDAPIClient is the client API for CDAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CDAPIClient interface {
	GetAllDeployments(ctx context.Context, in *DeploymentsQuery, opts ...grpc.CallOption) (*DeploymentsArray, error)
	GetDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Deployment, error)
	CreateDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error)
	ChangeImage(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error)
	ScaleDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error)
	UpdateManifest(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error)
	DeleteDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error)
}

type cDAPIClient struct {
	cc *grpc.ClientConn
}

func NewCDAPIClient(cc *grpc.ClientConn) CDAPIClient {
	return &cDAPIClient{cc}
}

func (c *cDAPIClient) GetAllDeployments(ctx context.Context, in *DeploymentsQuery, opts ...grpc.CallOption) (*DeploymentsArray, error) {
	out := new(DeploymentsArray)
	err := c.cc.Invoke(ctx, "/types.CDAPI/GetAllDeployments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDAPIClient) GetDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Deployment, error) {
	out := new(Deployment)
	err := c.cc.Invoke(ctx, "/types.CDAPI/GetDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDAPIClient) CreateDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/types.CDAPI/CreateDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDAPIClient) ChangeImage(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/types.CDAPI/ChangeImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDAPIClient) ScaleDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/types.CDAPI/ScaleDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDAPIClient) UpdateManifest(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/types.CDAPI/UpdateManifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDAPIClient) DeleteDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/types.CDAPI/DeleteDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDAPIServer is the server API for CDAPI service.
type CDAPIServer interface {
	GetAllDeployments(context.Context, *DeploymentsQuery) (*DeploymentsArray, error)
	GetDeployment(context.Context, *Deployment) (*Deployment, error)
	CreateDeployment(context.Context, *Deployment) (*Empty, error)
	ChangeImage(context.Context, *Deployment) (*Empty, error)
	ScaleDeployment(context.Context, *Deployment) (*Empty, error)
	UpdateManifest(context.Context, *Deployment) (*Empty, error)
	DeleteDeployment(context.Context, *Deployment) (*Empty, error)
}

func RegisterCDAPIServer(s *grpc.Server, srv CDAPIServer) {
	s.RegisterService(&_CDAPI_serviceDesc, srv)
}

func _CDAPI_GetAllDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).GetAllDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/GetAllDeployments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).GetAllDeployments(ctx, req.(*DeploymentsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDAPI_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/GetDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).GetDeployment(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDAPI_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/CreateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).CreateDeployment(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDAPI_ChangeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).ChangeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/ChangeImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).ChangeImage(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDAPI_ScaleDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).ScaleDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/ScaleDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).ScaleDeployment(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDAPI_UpdateManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).UpdateManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/UpdateManifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).UpdateManifest(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDAPI_DeleteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDAPIServer).DeleteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CDAPI/DeleteDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDAPIServer).DeleteDeployment(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

var _CDAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.CDAPI",
	HandlerType: (*CDAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllDeployments",
			Handler:    _CDAPI_GetAllDeployments_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _CDAPI_GetDeployment_Handler,
		},
		{
			MethodName: "CreateDeployment",
			Handler:    _CDAPI_CreateDeployment_Handler,
		},
		{
			MethodName: "ChangeImage",
			Handler:    _CDAPI_ChangeImage_Handler,
		},
		{
			MethodName: "ScaleDeployment",
			Handler:    _CDAPI_ScaleDeployment_Handler,
		},
		{
			MethodName: "UpdateManifest",
			Handler:    _CDAPI_UpdateManifest_Handler,
		},
		{
			MethodName: "DeleteDeployment",
			Handler:    _CDAPI_DeleteDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CD.proto",
}

func init() { proto.RegisterFile("CD.proto", fileDescriptor_CD_ade787ddd40b394c) }

var fileDescriptor_CD_ade787ddd40b394c = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x6e, 0xe2, 0x40,
	0x10, 0xc4, 0x18, 0x03, 0xdb, 0xec, 0xb2, 0xd0, 0x5a, 0xed, 0x8e, 0x38, 0xac, 0x90, 0x4f, 0x9c,
	0x50, 0x04, 0x41, 0xc9, 0x21, 0x17, 0xc7, 0x8e, 0x2c, 0x2b, 0x0f, 0x11, 0xa3, 0x7c, 0xc0, 0xc4,
	0x34, 0x60, 0xc9, 0x2f, 0xd9, 0x93, 0x83, 0xff, 0x23, 0xdf, 0x93, 0x6f, 0x8b, 0x3c, 0x38, 0xe0,
	0x88, 0x28, 0x82, 0x9b, 0xab, 0xba, 0xab, 0xa7, 0xaa, 0xdb, 0xd0, 0x36, 0xad, 0x71, 0x92, 0xc6,
	0x22, 0x46, 0x4d, 0xe4, 0x09, 0x65, 0xfa, 0x9b, 0x02, 0x60, 0x51, 0x12, 0xc4, 0x79, 0x48, 0x91,
	0xc0, 0x2e, 0xd4, 0x1d, 0x8b, 0x29, 0x43, 0x65, 0xa4, 0xba, 0x75, 0xc7, 0xc2, 0xbf, 0xd0, 0xbc,
	0x4e, 0x79, 0xe4, 0x6d, 0x58, 0x7d, 0xa8, 0x8c, 0x7e, 0xb8, 0x25, 0x2a, 0x78, 0x97, 0x92, 0xd8,
	0xb1, 0x98, 0x2a, 0x7b, 0x4b, 0x84, 0xff, 0x01, 0x8c, 0x54, 0xf8, 0x2b, 0xee, 0x09, 0xc7, 0x62,
	0x0d, 0x59, 0xab, 0x30, 0xc8, 0xa0, 0x75, 0x7b, 0xb9, 0x78, 0xe0, 0x21, 0x31, 0x4d, 0x0e, 0xfc,
	0x80, 0x38, 0x80, 0xf6, 0x3d, 0x8f, 0xfc, 0x15, 0x65, 0x82, 0x35, 0x65, 0x69, 0x87, 0x8b, 0x9a,
	0x4b, 0x49, 0xe0, 0x7b, 0x3c, 0x63, 0x2d, 0x39, 0x73, 0x87, 0xf5, 0x2b, 0xe8, 0xed, 0xfd, 0x67,
	0x8f, 0x2f, 0x94, 0xe6, 0x88, 0xd0, 0x98, 0xf3, 0x35, 0x95, 0x39, 0xe4, 0x37, 0xfe, 0x01, 0xed,
	0xce, 0x0f, 0x7d, 0x21, 0x83, 0xa8, 0xee, 0x16, 0xe8, 0xf6, 0x27, 0xb5, 0x91, 0xa6, 0x3c, 0xc7,
	0x29, 0x74, 0x96, 0x7b, 0x8e, 0x29, 0x43, 0x75, 0xd4, 0x99, 0xf4, 0xc7, 0x72, 0x5f, 0xe3, 0x7d,
	0xb7, 0x5b, 0xed, 0xd2, 0x5b, 0xa0, 0xdd, 0x84, 0x89, 0xc8, 0x27, 0xaf, 0x2a, 0x68, 0xa6, 0x65,
	0xcc, 0x1d, 0xb4, 0xa1, 0x6f, 0x93, 0x30, 0x82, 0xa0, 0xf2, 0x02, 0xfe, 0x3b, 0x98, 0xb3, 0xf5,
	0x3c, 0xf8, 0xa2, 0x20, 0xed, 0xe8, 0x35, 0xbc, 0x80, 0x5f, 0x36, 0x89, 0xca, 0x95, 0x0e, 0xcd,
	0x0c, 0x0e, 0x29, 0xbd, 0x86, 0x33, 0xe8, 0x99, 0x29, 0x71, 0x41, 0xdf, 0x6b, 0x7f, 0x96, 0x94,
	0x0c, 0xa0, 0xd7, 0xf0, 0x0c, 0x3a, 0xe6, 0x86, 0x47, 0x6b, 0x72, 0xc2, 0x62, 0x73, 0x47, 0x28,
	0xce, 0xe1, 0xf7, 0xc2, 0xe3, 0xc1, 0x89, 0xef, 0x4c, 0xa1, 0xfb, 0x94, 0x2c, 0xb9, 0xa0, 0xdd,
	0xa1, 0x8f, 0x10, 0xcd, 0x8a, 0x8b, 0x05, 0x74, 0x62, 0xa6, 0xe7, 0xa6, 0xfc, 0xeb, 0xa7, 0xef,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0xbf, 0x43, 0xe5, 0x01, 0x03, 0x00, 0x00,
}
