// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CDJobMessage.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CDJob struct {
	RepoID               int64    `protobuf:"varint,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Branch               string   `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	ArtifactID           int64    `protobuf:"varint,3,opt,name=artifactID,proto3" json:"artifactID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDJob) Reset()         { *m = CDJob{} }
func (m *CDJob) String() string { return proto.CompactTextString(m) }
func (*CDJob) ProtoMessage()    {}
func (*CDJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_CDJobMessage_e7ed4450a21a17ef, []int{0}
}
func (m *CDJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDJob.Unmarshal(m, b)
}
func (m *CDJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDJob.Marshal(b, m, deterministic)
}
func (dst *CDJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDJob.Merge(dst, src)
}
func (m *CDJob) XXX_Size() int {
	return xxx_messageInfo_CDJob.Size(m)
}
func (m *CDJob) XXX_DiscardUnknown() {
	xxx_messageInfo_CDJob.DiscardUnknown(m)
}

var xxx_messageInfo_CDJob proto.InternalMessageInfo

func (m *CDJob) GetRepoID() int64 {
	if m != nil {
		return m.RepoID
	}
	return 0
}

func (m *CDJob) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *CDJob) GetArtifactID() int64 {
	if m != nil {
		return m.ArtifactID
	}
	return 0
}

func init() {
	proto.RegisterType((*CDJob)(nil), "types.CDJob")
}

func init() { proto.RegisterFile("CDJobMessage.proto", fileDescriptor_CDJobMessage_e7ed4450a21a17ef) }

var fileDescriptor_CDJobMessage_e7ed4450a21a17ef = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x72, 0x76, 0xf1, 0xca,
	0x4f, 0xf2, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x56, 0x0a, 0xe7, 0x62, 0x05, 0x4b, 0x0a, 0x89, 0x71, 0xb1, 0x15,
	0xa5, 0x16, 0xe4, 0x7b, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x20, 0xf1,
	0xa4, 0xa2, 0xc4, 0xbc, 0xe4, 0x0c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48,
	0x8e, 0x8b, 0x2b, 0xb1, 0xa8, 0x24, 0x33, 0x2d, 0x31, 0xb9, 0xc4, 0xd3, 0x45, 0x82, 0x19, 0xac,
	0x07, 0x49, 0x24, 0x89, 0x0d, 0x6c, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x12, 0x57,
	0x7f, 0x7c, 0x00, 0x00, 0x00,
}
