// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CI.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Build struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GithubRepoID         int64                `protobuf:"varint,2,opt,name=GithubRepoID,proto3" json:"GithubRepoID,omitempty"`
	IsSuccessfull        bool                 `protobuf:"varint,3,opt,name=IsSuccessfull,proto3" json:"IsSuccessfull,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	Branch               string               `protobuf:"bytes,5,opt,name=Branch,proto3" json:"Branch,omitempty"`
	Stdout               string               `protobuf:"bytes,6,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_CI_1c5aff1f8b0afa28, []int{0}
}
func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (dst *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(dst, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Build) GetGithubRepoID() int64 {
	if m != nil {
		return m.GithubRepoID
	}
	return 0
}

func (m *Build) GetIsSuccessfull() bool {
	if m != nil {
		return m.IsSuccessfull
	}
	return false
}

func (m *Build) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Build) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Build) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

type BuildsQuery struct {
	RepoID               int64    `protobuf:"varint,1,opt,name=RepoID,proto3" json:"RepoID,omitempty"`
	Branch               string   `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildsQuery) Reset()         { *m = BuildsQuery{} }
func (m *BuildsQuery) String() string { return proto.CompactTextString(m) }
func (*BuildsQuery) ProtoMessage()    {}
func (*BuildsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_CI_1c5aff1f8b0afa28, []int{1}
}
func (m *BuildsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildsQuery.Unmarshal(m, b)
}
func (m *BuildsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildsQuery.Marshal(b, m, deterministic)
}
func (dst *BuildsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildsQuery.Merge(dst, src)
}
func (m *BuildsQuery) XXX_Size() int {
	return xxx_messageInfo_BuildsQuery.Size(m)
}
func (m *BuildsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BuildsQuery proto.InternalMessageInfo

func (m *BuildsQuery) GetRepoID() int64 {
	if m != nil {
		return m.RepoID
	}
	return 0
}

func (m *BuildsQuery) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuildsQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *BuildsQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BuildsArray struct {
	Total                int64    `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Builds               []*Build `protobuf:"bytes,2,rep,name=Builds,proto3" json:"Builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildsArray) Reset()         { *m = BuildsArray{} }
func (m *BuildsArray) String() string { return proto.CompactTextString(m) }
func (*BuildsArray) ProtoMessage()    {}
func (*BuildsArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_CI_1c5aff1f8b0afa28, []int{2}
}
func (m *BuildsArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildsArray.Unmarshal(m, b)
}
func (m *BuildsArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildsArray.Marshal(b, m, deterministic)
}
func (dst *BuildsArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildsArray.Merge(dst, src)
}
func (m *BuildsArray) XXX_Size() int {
	return xxx_messageInfo_BuildsArray.Size(m)
}
func (m *BuildsArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildsArray.DiscardUnknown(m)
}

var xxx_messageInfo_BuildsArray proto.InternalMessageInfo

func (m *BuildsArray) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BuildsArray) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type BuildArtifact struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BuildID              int64    `protobuf:"varint,2,opt,name=BuildID,proto3" json:"BuildID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildArtifact) Reset()         { *m = BuildArtifact{} }
func (m *BuildArtifact) String() string { return proto.CompactTextString(m) }
func (*BuildArtifact) ProtoMessage()    {}
func (*BuildArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_CI_1c5aff1f8b0afa28, []int{3}
}
func (m *BuildArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildArtifact.Unmarshal(m, b)
}
func (m *BuildArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildArtifact.Marshal(b, m, deterministic)
}
func (dst *BuildArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildArtifact.Merge(dst, src)
}
func (m *BuildArtifact) XXX_Size() int {
	return xxx_messageInfo_BuildArtifact.Size(m)
}
func (m *BuildArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_BuildArtifact proto.InternalMessageInfo

func (m *BuildArtifact) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BuildArtifact) GetBuildID() int64 {
	if m != nil {
		return m.BuildID
	}
	return 0
}

func (m *BuildArtifact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArtifactsArray struct {
	Total                int64            `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Artifacts            []*BuildArtifact `protobuf:"bytes,2,rep,name=Artifacts,proto3" json:"Artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ArtifactsArray) Reset()         { *m = ArtifactsArray{} }
func (m *ArtifactsArray) String() string { return proto.CompactTextString(m) }
func (*ArtifactsArray) ProtoMessage()    {}
func (*ArtifactsArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_CI_1c5aff1f8b0afa28, []int{4}
}
func (m *ArtifactsArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactsArray.Unmarshal(m, b)
}
func (m *ArtifactsArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactsArray.Marshal(b, m, deterministic)
}
func (dst *ArtifactsArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactsArray.Merge(dst, src)
}
func (m *ArtifactsArray) XXX_Size() int {
	return xxx_messageInfo_ArtifactsArray.Size(m)
}
func (m *ArtifactsArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactsArray.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactsArray proto.InternalMessageInfo

func (m *ArtifactsArray) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ArtifactsArray) GetArtifacts() []*BuildArtifact {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func init() {
	proto.RegisterType((*Build)(nil), "types.Build")
	proto.RegisterType((*BuildsQuery)(nil), "types.BuildsQuery")
	proto.RegisterType((*BuildsArray)(nil), "types.BuildsArray")
	proto.RegisterType((*BuildArtifact)(nil), "types.BuildArtifact")
	proto.RegisterType((*ArtifactsArray)(nil), "types.ArtifactsArray")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CIAPIClient is the client API for CIAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CIAPIClient interface {
	GetBuild(ctx context.Context, in *Build, opts ...grpc.CallOption) (*Build, error)
	GetBuildArtifact(ctx context.Context, in *BuildArtifact, opts ...grpc.CallOption) (*BuildArtifact, error)
	GetBuildArtifactByID(ctx context.Context, in *BuildArtifact, opts ...grpc.CallOption) (*BuildArtifact, error)
	GetAllBuilds(ctx context.Context, in *BuildsQuery, opts ...grpc.CallOption) (*BuildsArray, error)
	GetAllArtifacts(ctx context.Context, in *BuildsQuery, opts ...grpc.CallOption) (*ArtifactsArray, error)
}

type cIAPIClient struct {
	cc *grpc.ClientConn
}

func NewCIAPIClient(cc *grpc.ClientConn) CIAPIClient {
	return &cIAPIClient{cc}
}

func (c *cIAPIClient) GetBuild(ctx context.Context, in *Build, opts ...grpc.CallOption) (*Build, error) {
	out := new(Build)
	err := c.cc.Invoke(ctx, "/types.CIAPI/GetBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIAPIClient) GetBuildArtifact(ctx context.Context, in *BuildArtifact, opts ...grpc.CallOption) (*BuildArtifact, error) {
	out := new(BuildArtifact)
	err := c.cc.Invoke(ctx, "/types.CIAPI/GetBuildArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIAPIClient) GetBuildArtifactByID(ctx context.Context, in *BuildArtifact, opts ...grpc.CallOption) (*BuildArtifact, error) {
	out := new(BuildArtifact)
	err := c.cc.Invoke(ctx, "/types.CIAPI/GetBuildArtifactByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIAPIClient) GetAllBuilds(ctx context.Context, in *BuildsQuery, opts ...grpc.CallOption) (*BuildsArray, error) {
	out := new(BuildsArray)
	err := c.cc.Invoke(ctx, "/types.CIAPI/GetAllBuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIAPIClient) GetAllArtifacts(ctx context.Context, in *BuildsQuery, opts ...grpc.CallOption) (*ArtifactsArray, error) {
	out := new(ArtifactsArray)
	err := c.cc.Invoke(ctx, "/types.CIAPI/GetAllArtifacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CIAPIServer is the server API for CIAPI service.
type CIAPIServer interface {
	GetBuild(context.Context, *Build) (*Build, error)
	GetBuildArtifact(context.Context, *BuildArtifact) (*BuildArtifact, error)
	GetBuildArtifactByID(context.Context, *BuildArtifact) (*BuildArtifact, error)
	GetAllBuilds(context.Context, *BuildsQuery) (*BuildsArray, error)
	GetAllArtifacts(context.Context, *BuildsQuery) (*ArtifactsArray, error)
}

func RegisterCIAPIServer(s *grpc.Server, srv CIAPIServer) {
	s.RegisterService(&_CIAPI_serviceDesc, srv)
}

func _CIAPI_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Build)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIAPIServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CIAPI/GetBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIAPIServer).GetBuild(ctx, req.(*Build))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIAPI_GetBuildArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildArtifact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIAPIServer).GetBuildArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CIAPI/GetBuildArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIAPIServer).GetBuildArtifact(ctx, req.(*BuildArtifact))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIAPI_GetBuildArtifactByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildArtifact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIAPIServer).GetBuildArtifactByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CIAPI/GetBuildArtifactByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIAPIServer).GetBuildArtifactByID(ctx, req.(*BuildArtifact))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIAPI_GetAllBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIAPIServer).GetAllBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CIAPI/GetAllBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIAPIServer).GetAllBuilds(ctx, req.(*BuildsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIAPI_GetAllArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIAPIServer).GetAllArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.CIAPI/GetAllArtifacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIAPIServer).GetAllArtifacts(ctx, req.(*BuildsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _CIAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.CIAPI",
	HandlerType: (*CIAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBuild",
			Handler:    _CIAPI_GetBuild_Handler,
		},
		{
			MethodName: "GetBuildArtifact",
			Handler:    _CIAPI_GetBuildArtifact_Handler,
		},
		{
			MethodName: "GetBuildArtifactByID",
			Handler:    _CIAPI_GetBuildArtifactByID_Handler,
		},
		{
			MethodName: "GetAllBuilds",
			Handler:    _CIAPI_GetAllBuilds_Handler,
		},
		{
			MethodName: "GetAllArtifacts",
			Handler:    _CIAPI_GetAllArtifacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CI.proto",
}

func init() { proto.RegisterFile("CI.proto", fileDescriptor_CI_1c5aff1f8b0afa28) }

var fileDescriptor_CI_1c5aff1f8b0afa28 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x8e, 0x94, 0x40,
	0x10, 0x1d, 0x60, 0xc0, 0x99, 0x9a, 0xd9, 0xd5, 0x74, 0x46, 0xd3, 0xe1, 0x22, 0xe9, 0xec, 0x81,
	0x13, 0x9b, 0xe0, 0xc5, 0x93, 0x91, 0x59, 0x92, 0x49, 0x27, 0x6a, 0xd6, 0xde, 0x3d, 0x79, 0xeb,
	0x61, 0x7b, 0x58, 0x12, 0x10, 0x02, 0xcd, 0x81, 0xef, 0xf2, 0x0b, 0xfc, 0x33, 0x43, 0x37, 0xe0,
	0xa0, 0x13, 0x13, 0x6f, 0xfd, 0x5e, 0x3d, 0xaa, 0x5e, 0x3d, 0x0a, 0x56, 0x77, 0x34, 0xa8, 0xea,
	0x52, 0x96, 0xc8, 0x96, 0x5d, 0x25, 0x1a, 0xf7, 0x6d, 0x5a, 0x96, 0x69, 0x2e, 0x6e, 0x15, 0x79,
	0x6c, 0x4f, 0xb7, 0x32, 0x2b, 0x44, 0x23, 0x79, 0x51, 0x69, 0x1d, 0xf9, 0x69, 0x80, 0xbd, 0x6f,
	0xb3, 0xfc, 0x09, 0x5d, 0x83, 0x49, 0x63, 0x6c, 0x78, 0x86, 0x6f, 0x31, 0x93, 0xc6, 0x88, 0xc0,
	0xf6, 0x90, 0xc9, 0xe7, 0xf6, 0xc8, 0x44, 0x55, 0xd2, 0x18, 0x9b, 0xaa, 0x32, 0xe3, 0xd0, 0x0d,
	0x5c, 0xd1, 0xe6, 0xa1, 0x4d, 0x12, 0xd1, 0x34, 0xa7, 0x36, 0xcf, 0xb1, 0xe5, 0x19, 0xfe, 0x8a,
	0xcd, 0x49, 0x14, 0xc0, 0x32, 0xe6, 0x52, 0xe0, 0xa5, 0x67, 0xf8, 0x9b, 0xd0, 0x0d, 0xb4, 0xa7,
	0x60, 0xf4, 0x14, 0x3c, 0x8e, 0x9e, 0x98, 0xd2, 0xa1, 0x37, 0xe0, 0xec, 0x6b, 0xfe, 0x3d, 0x79,
	0xc6, 0xb6, 0x67, 0xf8, 0x6b, 0x36, 0xa0, 0x9e, 0x7f, 0x90, 0x4f, 0x65, 0x2b, 0xb1, 0xa3, 0x79,
	0x8d, 0x48, 0x0a, 0x1b, 0xb5, 0x42, 0xf3, 0xb5, 0x15, 0x75, 0xd7, 0xcb, 0x06, 0xcb, 0x7a, 0x99,
	0x01, 0x9d, 0xb5, 0x35, 0x67, 0x6d, 0x11, 0x2c, 0xef, 0x79, 0x2a, 0x94, 0x77, 0x8b, 0xa9, 0x37,
	0xda, 0x81, 0xfd, 0x29, 0x2b, 0x32, 0xa9, 0x3c, 0x5b, 0x4c, 0x03, 0x42, 0xc7, 0x41, 0x51, 0x5d,
	0xf3, 0xae, 0x17, 0x3d, 0x96, 0x92, 0xe7, 0xc3, 0x1c, 0x0d, 0xd0, 0x0d, 0x38, 0x5a, 0x84, 0x4d,
	0xcf, 0xf2, 0x37, 0xe1, 0x36, 0x50, 0xbf, 0x22, 0x50, 0x24, 0x1b, 0x6a, 0xe4, 0x33, 0x5c, 0xa9,
	0x57, 0x54, 0xcb, 0xec, 0xc4, 0x13, 0xf9, 0x57, 0xfc, 0x18, 0x5e, 0x28, 0xc1, 0x94, 0xfc, 0x08,
	0x7b, 0xbf, 0x5f, 0x78, 0xa1, 0xfd, 0xae, 0x99, 0x7a, 0x93, 0x6f, 0x70, 0x3d, 0x76, 0xfa, 0xa7,
	0xb9, 0x10, 0xd6, 0x93, 0x6e, 0xf0, 0xb7, 0x3b, 0xf7, 0x37, 0x16, 0xd9, 0x6f, 0x59, 0xf8, 0xc3,
	0x04, 0xfb, 0x8e, 0x46, 0xf7, 0x14, 0xf9, 0xb0, 0x3a, 0x08, 0xa9, 0xcf, 0x65, 0xb6, 0x96, 0x3b,
	0x43, 0x64, 0x81, 0x3e, 0xc2, 0xab, 0x51, 0x39, 0x6d, 0x78, 0x71, 0x90, 0x7b, 0x91, 0x25, 0x0b,
	0x14, 0xc3, 0xee, 0xcf, 0x0e, 0xfb, 0x8e, 0xc6, 0xff, 0xd9, 0xe5, 0x3d, 0x6c, 0x0f, 0x42, 0x46,
	0x79, 0xae, 0x63, 0x47, 0xe8, 0x5c, 0xa7, 0xef, 0xc5, 0x9d, 0x73, 0x2a, 0x3d, 0xb2, 0x40, 0x1f,
	0xe0, 0xa5, 0xfe, 0x72, 0x0a, 0xe2, 0xe2, 0xc7, 0xaf, 0x07, 0x6e, 0x9e, 0x3e, 0x59, 0x1c, 0x1d,
	0x75, 0xde, 0xef, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xc5, 0x38, 0xb1, 0x93, 0x03, 0x00,
	0x00,
}
