// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CIJobMessage.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CIJob struct {
	RepoURL              string   `protobuf:"bytes,1,opt,name=repoURL,proto3" json:"repoURL,omitempty"`
	Branch               string   `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	HeadSHA              string   `protobuf:"bytes,3,opt,name=headSHA,proto3" json:"headSHA,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken          string   `protobuf:"bytes,5,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RepoID               int64    `protobuf:"varint,6,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CIJob) Reset()         { *m = CIJob{} }
func (m *CIJob) String() string { return proto.CompactTextString(m) }
func (*CIJob) ProtoMessage()    {}
func (*CIJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_CIJobMessage_0066691548f7b4a0, []int{0}
}
func (m *CIJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CIJob.Unmarshal(m, b)
}
func (m *CIJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CIJob.Marshal(b, m, deterministic)
}
func (dst *CIJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CIJob.Merge(dst, src)
}
func (m *CIJob) XXX_Size() int {
	return xxx_messageInfo_CIJob.Size(m)
}
func (m *CIJob) XXX_DiscardUnknown() {
	xxx_messageInfo_CIJob.DiscardUnknown(m)
}

var xxx_messageInfo_CIJob proto.InternalMessageInfo

func (m *CIJob) GetRepoURL() string {
	if m != nil {
		return m.RepoURL
	}
	return ""
}

func (m *CIJob) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *CIJob) GetHeadSHA() string {
	if m != nil {
		return m.HeadSHA
	}
	return ""
}

func (m *CIJob) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CIJob) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CIJob) GetRepoID() int64 {
	if m != nil {
		return m.RepoID
	}
	return 0
}

func init() {
	proto.RegisterType((*CIJob)(nil), "types.CIJob")
}

func init() { proto.RegisterFile("CIJobMessage.proto", fileDescriptor_CIJobMessage_0066691548f7b4a0) }

var fileDescriptor_CIJobMessage_0066691548f7b4a0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x72, 0xf6, 0xf4, 0xca,
	0x4f, 0xf2, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x56, 0x5a, 0xc8, 0xc8, 0xc5, 0x0a, 0x96, 0x15, 0x92, 0xe0, 0x62,
	0x2f, 0x4a, 0x2d, 0xc8, 0x0f, 0x0d, 0xf2, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x85, 0xc4, 0xb8, 0xd8, 0x92, 0x8a, 0x12, 0xf3, 0x92, 0x33, 0x24, 0x98, 0xc0, 0x12, 0x50, 0x1e,
	0x48, 0x47, 0x46, 0x6a, 0x62, 0x4a, 0xb0, 0x87, 0xa3, 0x04, 0x33, 0x44, 0x07, 0x94, 0x2b, 0x24,
	0xc4, 0xc5, 0x52, 0x5a, 0x9c, 0x5a, 0x24, 0xc1, 0x02, 0x16, 0x06, 0xb3, 0x85, 0x14, 0xb8, 0xb8,
	0x13, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0x43, 0xf2, 0xb3, 0x53, 0xf3, 0x24, 0x58, 0xc1, 0x52, 0xc8,
	0x42, 0x20, 0x7b, 0x40, 0x56, 0x7a, 0xba, 0x48, 0xb0, 0x29, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79,
	0x49, 0x6c, 0x60, 0x17, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x56, 0x35, 0x51, 0xc7,
	0x00, 0x00, 0x00,
}
